version: "3"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: crawler
      MONGO_INITDB_ROOT_PASSWORD: A6968F2A93949455DE1E7C305AA13F61
    deploy:
      resources:
        limits:
          memory: 4G
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: A6968F2A93949455DE1E7C305AA13F61
      ME_CONFIG_MONGODB_URL: mongodb://crawler:A6968F2A93949455DE1E7C305AA13F61@mongo:27017/
#  crawler_server:
#    container_name: crawler_server
#    restart: always
#    build:
#      context: .
#      dockerfile: Dockerfile
#    environment:
#      MONGO_DB: crawler
#      MONGO_USER: crawler
#      MONGO_PASS: A6968F2A93949455DE1E7C305AA13F61
#      MONGO_HOST: mongo
#      MONGO_PORT: 27017

